/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as UnitsRouteImport } from './app/routes/units'
import { Route as SettingsRouteImport } from './app/routes/settings'
import { Route as ServicesRouteImport } from './app/routes/services'
import { Route as HomeRouteImport } from './app/routes/home'
import { Route as HelpRouteImport } from './app/routes/help'
import { Route as BarbershopStaffRouteImport } from './app/routes/barbershop-staff'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as AuthResetPasswordRouteImport } from './app/routes/auth/reset-password'
import { Route as AuthMfaVerificationRouteImport } from './app/routes/auth/mfa-verification'
import { Route as AuthLoginRouteImport } from './app/routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './app/routes/auth/forgot-password'
import { Route as AuthCreateBarbershopRouteImport } from './app/routes/auth/create-barbershop'

const UnitsRoute = UnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const BarbershopStaffRoute = BarbershopStaffRouteImport.update({
  id: '/barbershop-staff',
  path: '/barbershop-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMfaVerificationRoute = AuthMfaVerificationRouteImport.update({
  id: '/auth/mfa-verification',
  path: '/auth/mfa-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCreateBarbershopRoute = AuthCreateBarbershopRouteImport.update({
  id: '/auth/create-barbershop',
  path: '/auth/create-barbershop',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/barbershop-staff': typeof BarbershopStaffRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/units': typeof UnitsRoute
  '/auth/create-barbershop': typeof AuthCreateBarbershopRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa-verification': typeof AuthMfaVerificationRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/barbershop-staff': typeof BarbershopStaffRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/units': typeof UnitsRoute
  '/auth/create-barbershop': typeof AuthCreateBarbershopRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa-verification': typeof AuthMfaVerificationRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/barbershop-staff': typeof BarbershopStaffRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/units': typeof UnitsRoute
  '/auth/create-barbershop': typeof AuthCreateBarbershopRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa-verification': typeof AuthMfaVerificationRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/barbershop-staff'
    | '/help'
    | '/home'
    | '/services'
    | '/settings'
    | '/units'
    | '/auth/create-barbershop'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/mfa-verification'
    | '/auth/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/barbershop-staff'
    | '/help'
    | '/home'
    | '/services'
    | '/settings'
    | '/units'
    | '/auth/create-barbershop'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/mfa-verification'
    | '/auth/reset-password'
  id:
    | '__root__'
    | '/'
    | '/barbershop-staff'
    | '/help'
    | '/home'
    | '/services'
    | '/settings'
    | '/units'
    | '/auth/create-barbershop'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/mfa-verification'
    | '/auth/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BarbershopStaffRoute: typeof BarbershopStaffRoute
  HelpRoute: typeof HelpRoute
  HomeRoute: typeof HomeRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  UnitsRoute: typeof UnitsRoute
  AuthCreateBarbershopRoute: typeof AuthCreateBarbershopRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMfaVerificationRoute: typeof AuthMfaVerificationRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barbershop-staff': {
      id: '/barbershop-staff'
      path: '/barbershop-staff'
      fullPath: '/barbershop-staff'
      preLoaderRoute: typeof BarbershopStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/mfa-verification': {
      id: '/auth/mfa-verification'
      path: '/auth/mfa-verification'
      fullPath: '/auth/mfa-verification'
      preLoaderRoute: typeof AuthMfaVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/create-barbershop': {
      id: '/auth/create-barbershop'
      path: '/auth/create-barbershop'
      fullPath: '/auth/create-barbershop'
      preLoaderRoute: typeof AuthCreateBarbershopRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BarbershopStaffRoute: BarbershopStaffRoute,
  HelpRoute: HelpRoute,
  HomeRoute: HomeRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  UnitsRoute: UnitsRoute,
  AuthCreateBarbershopRoute: AuthCreateBarbershopRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthMfaVerificationRoute: AuthMfaVerificationRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
